enabledFeatures = [
    stopwatch,
    external-signature-endpoints,
    trusted-ca,
    status-lists,
    # dev-mode
    # entra,
    # lsp-potential
    # ...
]

disabledFeatures = [
    debug-endpoints
]
