name = "Keycloak"
authorizeUrl = "https://keycloak.theaustraliahack.com/realms/issuer/protocol/openid-connect/auth"
accessTokenUrl = "http://keycloak:8180/realms/issuer/protocol/openid-connect/token"
logoutUrl = "https://keycloak.theaustraliahack.com/realms/issuer/protocol/openid-connect/logout"
clientId = "issuer_api"
clientSecret = "issuer-api-secret"
